name       = "forunittest"
version    = "VERSION"
license    = "BSD 3-Clause License"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright 2025, Seyed Ali Ghasemi"

[build]
auto-executables = false
auto-tests       = false
auto-examples    = false
module-naming    = false

[install]
library = true

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[dependencies]
FACE    = {git="https://github.com/szaghi/FACE.git"}

[[test]]
name       = "test"
source-dir = "test"
main       = "test.f90"

[[example]]
name       = "demo"
source-dir = "example"
main       = "demo.f90"

[extra.ford]
project             = "ForUnitTest"
year                = "2025"
project_github      = "https://github.com/gha3mi/forunittest"
author              = "Seyed Ali Ghasemi"
email               = "info@gha3mi.com"
github              = "https://github.com/gha3mi"
license             = "BSD 3-Clause"
src_dir             = ["src", "example", "test"]
output_dir          = "doc"
source              = true
incl_src            = true
graph               = true
coloured_edges      = true
search              = true
print_creation_date = true
sort                = "permission-alpha"
display             = ["public", "private", "protected"]


[extra.fortitude.check]
ignore = ["S001", "C003"]